<a href="https://colab.research.google.com/github/achudnova/test-googlecollab/blob/main/dataprep_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# normalizing input data
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [3]:
# define dataset
X,y = make_classification(n_samples=1000, n_features=5, n_informative=5, n_redundant=0, random_state=1)

In [4]:
# calculate the min and max of each variable before transformation
min_before = np.min(X, axis=0)
max_before = np.max(X, axis=0)

In [5]:
# summarize data before the transform
print("Data before transformation - first 3 rows:")
print(X[:3, :])

Data before transformation - first 3 rows:
[[ 2.39324489 -5.77732048 -0.59062319 -2.08095322  1.04707034]
 [-0.45820294  1.94683482 -2.46471441  2.36590955 -0.73666725]
 [ 2.35162422 -1.00061698 -0.5946091   1.12531096 -0.65267587]]


In [6]:
# define the scaler
trans = MinMaxScaler()

In [8]:
# transform the data
X_norm = trans.fit_transform(X)

In [9]:
# calculate the min and max of each variable after transformation
min_after = np.min(X_norm, axis=0)
max_after = np.max(X_norm, axis=0)

In [11]:
# summarize data after the transform
print("Data after transformation - first 3 rows:")
print(X_norm[:3, :])

Data after transformation - first 3 rows:
[[0.77608466 0.0239289  0.48251588 0.18352101 0.59830036]
 [0.40400165 0.79590304 0.27369632 0.6331332  0.42104156]
 [0.77065362 0.50132629 0.48207176 0.5076991  0.4293882 ]]


In [12]:
print("\nMinimum values before transformation:")
print(min_before)
print("\nMaximum values before transformation:")
print(max_before)
print("\nMinimum values after transformation:")
print(min_after)
print("\nMaximum values after transformation:")
print(max_after)


Minimum values before transformation:
[-3.55425829 -6.01674626 -4.92105446 -3.89605694 -4.97356645]

Maximum values before transformation:
[4.10921382 3.98897142 4.0536372  5.99438395 5.08933368]

Minimum values after transformation:
[0. 0. 0. 0. 0.]

Maximum values after transformation:
[1. 1. 1. 1. 1.]
